services:
  db:
    image: postgres:16
    expose: 
        - "5432"
    env_file: backend/.env

  redis:
    image: redis:7-alpine
    expose:
      - "6379"

  backend:
    build: "./backend"
    ports: 
        - "8000:8000"
    env_file: backend/.env
    volumes:
      - ./backend:/app
